### ISSUE TITLE
More Tasks Please

### ISSUE THREAD

**Issue by doitliketyler** [ezeiger92/QuestWorld2#11]
Hey there. Thanks for continuing the development of QuestWorld2. There are 2 unused rows in the quest settings of the quest editor and I was wondering if you would consider using those rows for more tasks instead of just the 1 row? I have a quest that I would love to add up to 30 tasks which is not possible but it would be nice to have at least 27 possible tasks. I would even be happy with 1 additional row at this point. Thoughts?

**Comment by ezeiger92** [comment]
I'm still figuring out how I want stuff to work. Categories, quests, and tasks will likely end up supporting multiple pages similar to the way the entity selector got reworked. For now, my focus is on making the code easier to extend and fixing bugs. Eventually I'll come back to this, no eta's though.

**Comment by ezeiger92** [comment]
I'm closing this given #31 is in the works, which expands on this even more. Should be done soon.
