### ISSUE TITLE
Party issues, still

### ISSUE THREAD

**Issue by Lokarda2** [ezeiger92/QuestWorld2#110]
Hi, with the .12 version there is once again a problem with parties. I have reported a few weeks ago and its back 🤣 

The problem is when you want to invite someone to party it says that they already have a party even though they don't :/

**Comment by ezeiger92** [comment]
https://github.com/ezeiger92/QuestWorld2/releases/tag/v2.6.12a

I'm just gonna leave this open for a few weeks at this point and I hate parties.

**Comment by Lokarda2** [comment]
downloaded it again, uploaded it, restarted the server and ........... the big reveal .... the issue persists. 

Is there any additional info that I would be able to provide you to help locate the problem? (No errors in console or on startup)
We all hate parties at this point ... :/

**Comment by ezeiger92** [comment]
Could you give me your server's IP so I can hop on and take a look? I don't need any special permissions, I'll just test some things with invites and probably need to see a progress file or two.

**Comment by Lokarda2** [comment]
play.minefox.cz

**Comment by Lokarda2** [comment]
'0': {}
'1': {}
'10':
  '9':
    mission:
      d975d6fd-a385-459f-a159-a4e0fe45d072:
        progress: 1
    finished: true
    status: FINISHED
  '18':
    mission:
      60d9fddb-1e75-4f00-9452-35ba53e86fa7:
        progress: 1
    finished: true
    status: FINISHED
  '19':
    mission:
      4b99a9c4-18df-400d-9ed3-1b1f74dec050:
        progress: 0
    finished: true
    status: AVAILABLE
    cooldown: 2018-03-05-13-27
  '27':
    mission:
      d8979946-d1ae-442f-a203-7b762dd23ce1:
        progress: 2
        complete-until: 1520260603850
    finished: true
    status: REWARD_CLAIMABLE
    cooldown: 2018-02-12-00-23
  '28':
    mission:
      1611128f-86af-49f8-a65c-acaf19c09ad4:
        progress: 0
  '36':
    mission:
      60af896d-ab94-4f11-a113-c0aae2058fad:
        progress: 15
      71dd9d25-8005-4163-ac4d-75773dbec860:
        progress: 2
      b4d86e1a-91e0-4cd1-950d-8b1d8c0f12f8:
        progress: 2
      10000f93-3457-4dca-a5e1-60173e3c1ed3:
        progress: 10
      ff24303f-a50e-4bc7-a2b6-97f18aad2489:
        progress: 30
    finished: true
    status: FINISHED
  '10':
    mission:
      a8720713-612f-4f7c-bf34-15f5604fac2e:
        progress: 5
    finished: true
    status: REWARD_CLAIMABLE
  '11':
    mission:
      635d3bae-2f29-4704-9e0c-f74cc4f3ff98:
        progress: 10
    finished: true
    status: REWARD_CLAIMABLE
  '12':
    mission:
      cc50c904-0aa4-4806-8e6e-5abef840d6be:
        progress: 12
    finished: true
    status: REWARD_CLAIMABLE
  '20':
    mission:
      7ec99988-d058-4772-a34b-52b06f8c29d5:
        progress: 35
    finished: true
    status: REWARD_CLAIMABLE
  '46':
    mission:
      2ef8b5b9-1c4d-4cb5-a2e7-98758d0baf64:
        progress: 3
      b695448b-2420-48cf-9f3f-e85d7836e7c2:
        progress: 1
      123725c2-fd93-4407-8441-d92f30fa8ad0:
        progress: 1
      defd11bb-33d9-45fb-915c-8d0b067e25c6:
        progress: 8
      6a56ee1e-a23e-4196-bf75-888304175ca5:
        progress: 0
  '45':
    mission:
      cc1be39b-d53b-452d-b22a-2f3f0dc34964:
        progress: 576
  '37':
    mission:
      9b2589cb-be13-4a06-afbf-a13eb7bc168c:
        progress: 0
    finished: true
    status: AVAILABLE
    cooldown: 2018-02-10-03-16
party:
  members: []
  pending-requests: []
  associated: a45c891e-00b5-3d82-a559-b51fd5f87265
'11': {}
'13':
  '4':
    mission:
      32038f00-1a3d-4f71-8802-f280b161dbf8:
        progress: 11233
    finished: true
    status: FINISHED
  '0':
    mission:
      b1c05e04-ea9d-4273-99b7-bc2ce22b9882:
        progress: 300
    finished: true
    status: FINISHED
  '1':
    mission:
      29f717bf-6f91-4b20-b4f3-c5b42201b9b4:
        progress: 900
    finished: true
    status: FINISHED
  '2':
    mission:
      081553c2-1d89-4928-a9a2-ae28b2c4b194:
        progress: 3000
    finished: true
    status: FINISHED
  '3':
    mission:
      9f2dfbd3-16fb-4c4f-8aea-fc4bdb308c76:
        progress: 6000
    finished: true
    status: FINISHED
  '12':
    mission:
      a9de51a1-1080-4566-8f6c-81217f7571a1:
        progress: 5
  '9':
    mission:
      f62b53dd-d278-4cd9-9294-ec842c53384d:
        progress: 10
    finished: true
    status: FINISHED
  '13':
    mission:
      36bff531-3b36-41f8-b775-4a3f438c1e8c:
        progress: 5
  '10':
    mission:
      c03fc813-d60b-4c1a-9f23-fc86ea2c735e:
        progress: 30
    finished: true
    status: REWARD_CLAIMABLE
  '11':
    mission:
      fbfc9d8d-38dc-4503-8643-1c1105241054:
        progress: 94
  '5':
    mission:
      c3357279-27c3-4442-acf0-4dcfb39ae48e:
        progress: 10
      d090c188-2873-451d-9392-baaef5134024:
        progress: 128
      de30514b-1b0b-4f54-a1cc-9e462dd34904:
        progress: 128
      b3746b63-cd7c-43a3-91a5-4d13eeeee47f:
        progress: 128
      0c57fdab-3291-4293-9ff4-67d54d29f7f0:
        progress: 111
  '8':
    mission:
      87771816-e6e0-4f0c-9715-d977697fdf16:
        progress: 11
'55':
  '20':
    mission:
      44fc7657-99e9-424f-b543-d8d1c35bb309:
        progress: 1
      d7931760-1c7c-48b1-82a5-6136f6e066d5:
        progress: 32
      b32fbbdf-fa5e-471d-adbe-d1856d9dad2b:
        progress: 32
    finished: true
    status: FINISHED
  '21':
    mission:
      a27afe71-2282-4fad-846f-ec160c527054:
        progress: 1
      c43df3fb-09b7-449e-a82e-cbb1976b2a97:
        progress: 1
      3df15beb-ed2f-4841-b3a5-dca1933946c9:
        progress: 1
      4bbb4991-917c-47c6-8b90-005a2e9890de:
        progress: 1
      edd17fc6-718f-4c7a-9c17-3f8cae4197b1:
        progress: 1
      aafc29ef-1331-400a-8c7c-11c89fd84840:
        progress: 1
    finished: true
    status: FINISHED
  '22':
    mission:
      7dd2461c-2d5e-4f3f-aa0b-8457174a1f78:
        progress: 1
    finished: true
    status: REWARD_CLAIMABLE
  '19':
    mission:
      3cafa546-8d08-4852-ad3b-d7e3180711af:
        progress: 1
    finished: true
    status: FINISHED


playerdata for a45c891e-00b5-3d82-a559-b51fd5f87265

**Comment by Lokarda2** [comment]
couldnt the problem be being associated with myself? :D

**Comment by ezeiger92** [comment]
Well I for one did not expect an auth server in another language.

**Comment by Lokarda2** [comment]
😆 😆 😆 😆 😆 
Im so sorry :D 

/register password passwordonceagain
then commands are the same.. if you need anyhting else ont he server /pm Loky2 and i will answer :DD

**Comment by ezeiger92** [comment]
https://github.com/ezeiger92/QuestWorld2/releases/tag/v2.6.13

With any luck this fixes it.

**Comment by Lokarda2** [comment]
Fixed. You are a legend. Keep it up. 

Works perfectly!!!! 👍 😆

**Comment by Lokarda2** [comment]
I just got an idea for a feature... mb you could add automatic parties based on friendship. Some friends plugin? :D

**Comment by ezeiger92** [comment]
There has already been a request for compatibility with the [Parties](https://www.spigotmc.org/resources/parties.3709/) plugin, and personally I'd like the ability to hook into mcmmo parties (because my server uses them). I'm currently planning some way to hook into party creation.

Glad to hear that I've actually solved your issue this time (omg finally). If you run into any more issues, definitely let me know!
