### ISSUE TITLE
Editor GUI doesn't show categories correctly

### ISSUE THREAD

**Issue by unlimitedsola** [ezeiger92/QuestWorld2#112]
I uploaded a video to show this: https://www.youtube.com/watch?v=cU1gWqYPd00&feature=youtu.be

**Comment by ezeiger92** [comment]
What server and plugin versions do you have? I cannot replicate this using the latest QuestWorld and spigot 1.12.2.

**Comment by unlimitedsola** [comment]
I built the plugin from latest source code from master branch, MC version is 1.12.2

**Comment by unlimitedsola** [comment]
@ezeiger92 I can't see the tagged commit on master branch, did you delete it?

**Comment by ezeiger92** [comment]
I forked the previous release and applied a few patches, here's the commit: 6c415491066c6aa07f8d237c7996b172b5c9a693.
I didn't see much point in keeping the branch around when a tag does all I need.
