### ISSUE TITLE
Extensions can fail to load if their dependant plugin isn't loaded yet

### ISSUE THREAD

**Issue by UltraFaceguy** [ezeiger92/QuestWorld2#115]
Citizens extension can fail to load if citizens decides to load after QuestWorld, as the dependency for the extension is missing. Placing Citizens as a softdepend solves this, but I doubt that that's a viable solution.

Latest version, master branch.

**Comment by ezeiger92** [comment]
I just forced Citizens to load after QuestWorld 2.6.13, and the citizens extension was able to load without issue.
