### ISSUE TITLE
Catagories don't show up in the Catagories menu

### ISSUE THREAD

**Issue by UltraFaceguy** [ezeiger92/QuestWorld2#116]
I'm not seeing anything at all in the categories in /questeditor gui. Interestingly enough, I can create and name those categories, and they show up in /quests, but old categories and new categories alike fail to show, so not much can be done with them.

**Comment by ezeiger92** [comment]
I cannot replicate this on 2.6.13. I suspect you tried to build the code on the repo, which is not production ready.

**Comment by poma123** [comment]
@UltraFaceguy Build the jar from the source here: https://github.com/ezeiger92/QuestWorld2/releases
or use the pre-built jar on the same link above.
