### ISSUE TITLE
multiple servers problem

### ISSUE THREAD

**Issue by sumdream** [ezeiger92/QuestWorld2#117]
I have multiple configured servers, and it is possible to synchronize all server quests tasks.All the server have same quests.

**Comment by UltraFaceguy** [comment]
Well, SQL support would solve this issue, and I personally would like that from Questworld. 

Also something like that would be a necessity on any large RPG server that uses bungiecoord to create instances/shards to handle the load over multiple servers running the same game

**Comment by UltraFaceguy** [comment]
Fair point about the DB support, I know alllllll about QW's storage woes haha. It hangs my server for a solid 15 seconds if I delete a quest at this point, and I only have about 30 quests.

Testing/debugging would be a breeze though, you'd just have to confirm that values are pulled in the moment from the database, and that they're set in the database correctly. Once that's established, it's pretty certain that it will automatically work across servers. To be sure though, I'd be willing to test it out on a multi-server setup, should it ever reach that point.
