### ISSUE TITLE
Fishing and time quest bug

### ISSUE THREAD

**Issue by Midnaait** [ezeiger92/QuestWorld2#118]
Hello! I found a problem the other day with the fishing quests.
If you throw the required item to the ground, and hook it with the fishing rod, it still counts up, so if you throw 64 fish to the ground and hook it with the fishing rod, the quest says you progressed, for example, 64/100.

About the time quest:

Is it normal if it starts counting since you first join the server? Is there a way to count it from the time it unlocks the quest?

Thanks! (And obligatory sorry for bad english lol)

**Comment by ezeiger92** [comment]
Oh boy, did not thing about pulling in items with a rod. Whoops.

Unfortunately "play time" has always counted the total time played on the server. This is old behavior and I don't have a quick way to change it :(
