### ISSUE TITLE
Force Save Quests

### ISSUE THREAD

**Issue by GershonR** [ezeiger92/QuestWorld2#12]
I noticed that a lot of time I would make a quest and it's all working but after a restart it dissapears, i'm assuming because for some reason it waits on restart to save the file or it just never saves it at all from memory, I was wondering if it's possible to add a command to save all quests.

**Comment by ezeiger92** [comment]
Looks like save is only called in once place - onDisable. That's just silly. I'll add a command really quick and maybe an auto-save timer

**Comment by GershonR** [comment]
Awesome, thank you so much!

**Comment by ezeiger92** [comment]
There we go, stopped being lazy and pushed out a [new release](https://github.com/ezeiger92/QuestWorld2/releases/tag/v2.6.3-beta). It has a save function and autosave feature with configurable interval.
