### ISSUE TITLE
Quest Location Tasks

### ISSUE THREAD

**Issue by Peculiarityy** [ezeiger92/QuestWorld2#122]
**Concept:** The idea is similar to the Citizens Extention, where when doing a quest the NPC emits particles. Would it be possible to add it emit particles for Block Locations also? I might make a pull request and try.

**Comment by ezeiger92** [comment]
The Extras extension has a click block mission type, and there is an open request for adding particles ezeiger92/QuestWorld-Extensions#2. Unless you are referring to reach location missions, I'll close this request in favor of the other one.

**Comment by Peculiarityy** [comment]
Awesome, sorry I had not previously seen that message.

**Comment by Peculiarityy** [comment]
Awesome, sorry I had not previously seen that message.

**Comment by ezeiger92** [comment]
No worries, I'm really not sure why I have 2 places for issues :/
