### ISSUE TITLE
Work on 1.9 ?

### ISSUE THREAD

**Issue by SyndromHD** [ezeiger92/QuestWorld2#123]
Hey I've tried the more recent build and I can see him in /pl command but don't work...
I'm on spigot version 1.9

Any solutions ?

**Comment by ezeiger92** [comment]
The plugin didn't load because I'm not supporting old server versions, sorry. I don't know off hand which of my builds, if any, work with 1.9. [MrCookieSlime's original plugin](https://www.spigotmc.org/resources/quest-world.6903/) appears to.
