### ISSUE TITLE
Issues with players name appearing in quest dialogue

### ISSUE THREAD

**Issue by razaphale** [ezeiger92/QuestWorld2#126]
Not exactly an issue, just need help and don't know where to go. :/ 

Can't seem to get the players name to pop up in chat when an NPC is supposed to address them and can't find the information I need for it. Been looking for a couple of hours now and my eyes are pretty tired. So since I couldn't figure it out I just came here since the wiki here didn't have anything either. 

For instance the npc asks the players name, there's a pause and then "&bWelcomer Sage&f: ... Ah I see it's <player> , well, welcome too Onyxward." but <player> doesn't work any more. So I'm not sure what I'm supposed to put in its place.

**Comment by ezeiger92** [comment]
Have you tried using `@p`, or the older `<player>`?

**Comment by ezeiger92** [comment]
I need to know what version you are using and see the dialogue file then :/

**Comment by razaphale** [comment]
QuestWorld-2.7.0-RC2.jar is the one I'm using at the moment and the citizens extension is QW-Citizens-1.4.0.jar

**Comment by ezeiger92** [comment]
Run `/qe export some_name` and send it to me. 

Dialogues replace `@p` and `<player>` with player.getName() before sending messages or running commands. There is no reason for this to fail.
If you are using quest descriptions, instead (the virtual book pop-up with `ACCEPT_QUEST`), there is currently no placeholder support.
