### ISSUE TITLE
Enabled/Disabled option in a quest's settings

### ISSUE THREAD

**Issue by UltraFaceguy** [ezeiger92/QuestWorld2#129]
There should probably be an enabled/disabled option (that defaults to disabled on quest creation) within quests. 

For a brief period of time instantly after creation, a quest can be completed. Which means if the user is very quick has stone in their invy, they can just... turn it in and just... lock themselves out of that quest forever, as they've completed it. Additionally, a quest editor may inadvertently trigger something like the location check while clicking through quest objectives, causing them to have to clear the quest's data in order to properly test it later.

I've been evading these issues as best as I can by on quest creation setting the quest requirement to a dummy quest that can't be completed, but that's getting a bit old...

**Comment by Zicerite** [comment]
I mean, you could lock the quest with a permission before working on it, but i guess a proper enable/disable button would be... cleaner? I guess?

**Comment by Worlfy** [comment]
I think it would both be cleaner and faster

**Comment by UltraFaceguy** [comment]
Doesn't really work as well if you have the * node. You could set it up so that you also have a negative permission and set that as the requirement, but recall that an (un)lucky user can still reach the quest while you're doing setup. They really should be disabled by default.
