### ISSUE TITLE
1.13 extension citizen

### ISSUE THREAD

**Issue by Yukyxy** [ezeiger92/QuestWorld2#138]
Hello the extension QW-Citizens-1.4.0.jar 
does not work in 1.13, it is impossible to select a NPC for quests.

**Comment by ezeiger92** [comment]
I haven't built anything to support 1.13 yet, but if there's a stacktrace I could take a look.

**Comment by Yukyxy** [comment]
https://pastebin.com/WvAgVJ6V

**Comment by Yukyxy** [comment]
fail sorry

**Comment by ezeiger92** [comment]
That one has nothing to do with QW-Citizens, that is QW-Extras failing to load because it was built against 1.12 and and Spigot’s bytecode transformations aren’t applied to it.

**Comment by ezeiger92** [comment]
Similar problem for QW-Citizens then. Not that surprising. Since 1.13 is not supported yet and this is entirely cause by 1.13, I'm going to close this issue. I'm in a bad spot to update extensions right now, but I'll see what's possible.
