### ISSUE TITLE
"Kill" and "Kill Named Mob" objective issue

### ISSUE THREAD

**Issue by dallin1016** [ezeiger92/QuestWorld2#146]
When making an objective for "Kill"/"Kill Named Mob", when i click to change what type of mob it is, this pops up:

> An Internal Error Occurred, Please Contact an Admin!

Could this be because I'm running on 1.13? If so is there an ETA on an update to fix this?

Console Warnings:

> 19.12 22:38:37 [Server] WARN java.lang.IllegalStateException: No version adapter found that supports "makeSpawnEgg"
19.12 22:38:37 [Server] WARN at com.questworld.util.MultiAdapter.dispatch(MultiAdapter.java:131)
19.12 22:38:37 [Server] WARN at com.questworld.util.MultiAdapter.makeSpawnEgg(MultiAdapter.java:54)
19.12 22:38:37 [Server] WARN at com.questworld.util.ItemBuilder.mob(ItemBuilder.java:279)
19.12 22:38:37 [Server] WARN at com.questworld.util.EntityTools.getEntityDisplay(EntityTools.java:84)
19.12 22:38:37 [Server] WARN at com.questworld.api.menu.QBDialogue.openQuestMissionEntityEditor(QBDialogue.java:139)
19.12 22:38:37 [Server] WARN at com.questworld.api.menu.MissionButton.lambda$entity$2(MissionButton.java:68)
19.12 22:38:37 [Server] WARN at com.questworld.api.menu.Menu.click(Menu.java:96)
19.12 22:38:37 [Server] WARN at com.questworld.listener.MenuListener.onInventoryClick(MenuListener.java:33)
19.12 22:38:37 [Server] WARN at sun.reflect.GeneratedMethodAccessor50.invoke(Unknown Source)
19.12 22:38:37 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19.12 22:38:37 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
19.12 22:38:37 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
19.12 22:38:37 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
19.12 22:38:37 [Server] WARN at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
19.12 22:38:37 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
19.12 22:38:37 [Server] WARN at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2127)
19.12 22:38:37 [Server] WARN at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:33)
19.12 22:38:37 [Server] WARN at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:10)
19.12 22:38:37 [Server] WARN at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
19.12 22:38:37 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
19.12 22:38:37 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
19.12 22:38:37 [Server] WARN at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
19.12 22:38:37 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900)
19.12 22:38:37 [Server] WARN at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
19.12 22:38:37 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
19.12 22:38:37 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
19.12 22:38:37 [Server] WARN at java.lang.Thread.run(Thread.java:748)
19.12 22:39:35 [Server] WARN java.lang.ClassCastException: net.minecraft.server.v1_13_R2.ChatMessage cannot be cast to java.lang.String
19.12 22:39:35 [Server] WARN at com.questworld.util.Reflect.nmsGetItemName(Reflect.java:89)
19.12 22:39:35 [Server] WARN at com.questworld.util.Text.itemName(Text.java:175)
19.12 22:39:35 [Server] WARN at com.questworld.extension.builtin.CraftMission.userInstanceDescription(CraftMission.java:34)
19.12 22:39:35 [Server] WARN at com.questworld.api.MissionType.userDescription(MissionType.java:32)
19.12 22:39:35 [Server] WARN at com.questworld.quest.Mission.getText(Mission.java:156)
19.12 22:39:35 [Server] WARN at com.questworld.api.menu.MissionButton.missionName(MissionButton.java:105)
19.12 22:39:35 [Server] WARN at com.questworld.api.MissionType.buildMenu(MissionType.java:110)
19.12 22:39:35 [Server] WARN at com.questworld.api.menu.QuestBook.openQuestMissionEditor(QuestBook.java:1092)
19.12 22:39:35 [Server] WARN at com.questworld.api.menu.MissionButton.apply(MissionButton.java:245)
19.12 22:39:35 [Server] WARN at com.questworld.api.menu.MissionButton.lambda$simpleButton$17(MissionButton.java:250)
19.12 22:39:35 [Server] WARN at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
19.12 22:39:35 [Server] WARN at com.questworld.api.menu.Menu.click(Menu.java:96)
19.12 22:39:35 [Server] WARN at com.questworld.listener.MenuListener.onInventoryClick(MenuListener.java:33)
19.12 22:39:35 [Server] WARN at sun.reflect.GeneratedMethodAccessor50.invoke(Unknown Source)
19.12 22:39:35 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19.12 22:39:35 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
19.12 22:39:35 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
19.12 22:39:35 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
19.12 22:39:35 [Server] WARN at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
19.12 22:39:35 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
19.12 22:39:35 [Server] WARN at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2127)
19.12 22:39:35 [Server] WARN at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:33)
19.12 22:39:35 [Server] WARN at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:10)
19.12 22:39:35 [Server] WARN at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
19.12 22:39:35 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
19.12 22:39:35 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
19.12 22:39:35 [Server] WARN at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
19.12 22:39:35 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900)
19.12 22:39:35 [Server] WARN at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
19.12 22:39:35 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
19.12 22:39:35 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
19.12 22:39:35 [Server] WARN at java.lang.Thread.run(Thread.java:748)
19.12 22:39:35 [Server] WARN java.lang.ClassCastException: net.minecraft.server.v1_13_R2.ChatMessage cannot be cast to java.lang.String
19.12 22:39:35 [Server] WARN at com.questworld.util.Reflect.nmsGetItemName(Reflect.java:89)
19.12 22:39:35 [Server] WARN at com.questworld.util.Text.itemName(Text.java:175)
19.12 22:39:35 [Server] WARN at com.questworld.api.menu.MissionButton.item(MissionButton.java:38)
19.12 22:39:35 [Server] WARN at com.questworld.extension.builtin.CraftMission.layoutMenu(CraftMission.java:97)
19.12 22:39:35 [Server] WARN at com.questworld.api.MissionType.buildMenu(MissionType.java:114)
19.12 22:39:35 [Server] WARN at com.questworld.api.menu.QuestBook.openQuestMissionEditor(QuestBook.java:1092)
19.12 22:39:35 [Server] WARN at com.questworld.api.menu.MissionButton.apply(MissionButton.java:245)
19.12 22:39:35 [Server] WARN at com.questworld.api.menu.MissionButton.lambda$simpleButton$17(MissionButton.java:250)
19.12 22:39:35 [Server] WARN at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
19.12 22:39:35 [Server] WARN at com.questworld.api.menu.Menu.click(Menu.java:96)
19.12 22:39:35 [Server] WARN at com.questworld.listener.MenuListener.onInventoryClick(MenuListener.java:33)
19.12 22:39:35 [Server] WARN at sun.reflect.GeneratedMethodAccessor50.invoke(Unknown Source)
19.12 22:39:35 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19.12 22:39:35 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
19.12 22:39:35 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
19.12 22:39:35 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
19.12 22:39:35 [Server] WARN at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
19.12 22:39:35 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
19.12 22:39:35 [Server] WARN at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2127)
19.12 22:39:35 [Server] WARN at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:33)
19.12 22:39:35 [Server] WARN at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:10)
19.12 22:39:35 [Server] WARN at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
19.12 22:39:35 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
19.12 22:39:35 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
19.12 22:39:35 [Server] WARN at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
19.12 22:39:35 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900)
19.12 22:39:35 [Server] WARN at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
19.12 22:39:35 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
19.12 22:39:35 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
19.12 22:39:35 [Server] WARN at java.lang.Thread.run(Thread.java:748)
19.12 22:39:37 [Server] WARN java.lang.ClassCastException: net.minecraft.server.v1_13_R2.ChatMessage cannot be cast to java.lang.String
19.12 22:39:37 [Server] WARN at com.questworld.util.Reflect.nmsGetItemName(Reflect.java:89)
19.12 22:39:37 [Server] WARN at com.questworld.util.Text.itemName(Text.java:175)
19.12 22:39:37 [Server] WARN at com.questworld.extension.builtin.CraftMission.userInstanceDescription(CraftMission.java:34)
19.12 22:39:37 [Server] WARN at com.questworld.api.MissionType.userDescription(MissionType.java:32)
19.12 22:39:37 [Server] WARN at com.questworld.quest.Mission.getText(Mission.java:156)
19.12 22:39:37 [Server] WARN at com.questworld.api.menu.MissionButton.missionName(MissionButton.java:105)
19.12 22:39:37 [Server] WARN at com.questworld.api.MissionType.buildMenu(MissionType.java:110)
19.12 22:39:37 [Server] WARN at com.questworld.api.menu.QuestBook.openQuestMissionEditor(QuestBook.java:1092)
19.12 22:39:37 [Server] WARN at com.questworld.api.menu.MissionButton.apply(MissionButton.java:245)
19.12 22:39:37 [Server] WARN at com.questworld.api.menu.MissionButton.lambda$simpleButton$17(MissionButton.java:250)
19.12 22:39:37 [Server] WARN at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
19.12 22:39:37 [Server] WARN at com.questworld.api.menu.Menu.click(Menu.java:96)
19.12 22:39:37 [Server] WARN at com.questworld.listener.MenuListener.onInventoryClick(MenuListener.java:33)
19.12 22:39:37 [Server] WARN at sun.reflect.GeneratedMethodAccessor50.invoke(Unknown Source)
19.12 22:39:37 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19.12 22:39:37 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
19.12 22:39:37 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
19.12 22:39:37 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
19.12 22:39:37 [Server] WARN at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
19.12 22:39:37 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
19.12 22:39:37 [Server] WARN at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2127)
19.12 22:39:37 [Server] WARN at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:33)
19.12 22:39:37 [Server] WARN at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:10)
19.12 22:39:37 [Server] WARN at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
19.12 22:39:37 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
19.12 22:39:37 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
19.12 22:39:37 [Server] WARN at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
19.12 22:39:37 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900)
19.12 22:39:37 [Server] WARN at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
19.12 22:39:37 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
19.12 22:39:37 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
19.12 22:39:37 [Server] WARN at java.lang.Thread.run(Thread.java:748)
19.12 22:39:37 [Server] WARN java.lang.ClassCastException: net.minecraft.server.v1_13_R2.ChatMessage cannot be cast to java.lang.String
19.12 22:39:37 [Server] WARN at com.questworld.util.Reflect.nmsGetItemName(Reflect.java:89)
19.12 22:39:37 [Server] WARN at com.questworld.util.Text.itemName(Text.java:175)
19.12 22:39:37 [Server] WARN at com.questworld.api.menu.MissionButton.item(MissionButton.java:38)
19.12 22:39:37 [Server] WARN at com.questworld.extension.builtin.CraftMission.layoutMenu(CraftMission.java:97)
19.12 22:39:37 [Server] WARN at com.questworld.api.MissionType.buildMenu(MissionType.java:114)
19.12 22:39:37 [Server] WARN at com.questworld.api.menu.QuestBook.openQuestMissionEditor(QuestBook.java:1092)
19.12 22:39:37 [Server] WARN at com.questworld.api.menu.MissionButton.apply(MissionButton.java:245)
19.12 22:39:37 [Server] WARN at com.questworld.api.menu.MissionButton.lambda$simpleButton$17(MissionButton.java:250)
19.12 22:39:37 [Server] WARN at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
19.12 22:39:37 [Server] WARN at com.questworld.api.menu.Menu.click(Menu.java:96)
19.12 22:39:37 [Server] WARN at com.questworld.listener.MenuListener.onInventoryClick(MenuListener.java:33)
19.12 22:39:37 [Server] WARN at sun.reflect.GeneratedMethodAccessor50.invoke(Unknown Source)
19.12 22:39:37 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19.12 22:39:37 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
19.12 22:39:37 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
19.12 22:39:37 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
19.12 22:39:37 [Server] WARN at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
19.12 22:39:37 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
19.12 22:39:37 [Server] WARN at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2127)
19.12 22:39:37 [Server] WARN at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:33)
19.12 22:39:37 [Server] WARN at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:10)
19.12 22:39:37 [Server] WARN at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
19.12 22:39:37 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
19.12 22:39:37 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
19.12 22:39:37 [Server] WARN at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
19.12 22:39:37 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900)
19.12 22:39:37 [Server] WARN at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
19.12 22:39:37 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
19.12 22:39:37 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
19.12 22:39:37 [Server] WARN at java.lang.Thread.run(Thread.java:748)

**Comment by ezeiger92** [comment]
"java.lang.ClassCastException: net.minecraft.server.v1_13_R2.ChatMessage cannot be cast to java.lang.String"
Yep, issue with there (still) not being a 1.13 version.

**Comment by ezeiger92** [comment]
Closing this as I have an alpha build with support for 1.13 and 1.12, just be cautious with it because it's definitely alpha.

**Comment by dallin1016** [comment]
Hey, it still is not letting me change the mob type. The same message appears in game, and this is what appears in console:

> 16.01 00:53:53 [Server] INFO [QuestWorld] Caching CurrentAdapter (1_13_R2) for method makeSpawnEgg
16.01 00:53:53 [Server] WARN java.lang.NullPointerException
16.01 00:53:53 [Server] WARN at com.questworld.util.ItemBuilder.wrapText(ItemBuilder.java:336)
16.01 00:53:53 [Server] WARN at com.questworld.api.menu.QBDialogue.openQuestMissionEntityEditor(QBDialogue.java:141)
16.01 00:53:53 [Server] WARN at com.questworld.api.menu.MissionButton.lambda$entity$2(MissionButton.java:70)
16.01 00:53:53 [Server] WARN at com.questworld.api.menu.Menu.click(Menu.java:96)
16.01 00:53:53 [Server] WARN at com.questworld.listener.MenuListener.onInventoryClick(MenuListener.java:33)
16.01 00:53:53 [Server] WARN at sun.reflect.GeneratedMethodAccessor128.invoke(Unknown Source)
16.01 00:53:53 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16.01 00:53:53 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
16.01 00:53:53 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305)
16.01 00:53:53 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
16.01 00:53:53 [Server] WARN at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
16.01 00:53:53 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
16.01 00:53:53 [Server] WARN at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2122)
16.01 00:53:53 [Server] WARN at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:33)
16.01 00:53:53 [Server] WARN at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:10)
16.01 00:53:53 [Server] WARN at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
16.01 00:53:53 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
16.01 00:53:53 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
16.01 00:53:53 [Server] WARN at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
16.01 00:53:53 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896)
16.01 00:53:53 [Server] WARN at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
16.01 00:53:53 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
16.01 00:53:53 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
16.01 00:53:53 [Server] WARN at java.lang.Thread.run(Thread.java:748)
