### ISSUE TITLE
Mission Resets

### ISSUE THREAD

**Issue by Peculiarityy** [ezeiger92/QuestWorld2#147]
Whenever restarting the server all of our missions reset, every time. We're running spigot 1.12.2, and have tried both QuestWorld 7 and 8.

**Comment by ezeiger92** [comment]
The cooldowns reset or quest progress is lost? And I would expect errors in the log from something like that, could you take a look?

**Comment by ezeiger92** [comment]
Wait, you start up your server with the citizens extension and make missions with it, then after a restart they're invalid? Does the extension get deleted?

**Comment by Peculiarityy** [comment]
Yeah, that's currently one of the issues sadly.  The extension never gets deleted from the file (Which is the odd thing)

**Comment by ezeiger92** [comment]
I cannot replicate lost progress, but there is a mission loading issue.
