### ISSUE TITLE
Console spamming this error

### ISSUE THREAD

**Issue by dejakob1** [ezeiger92/QuestWorld2#148]
Spigot: 1.13.2
Questworld: QuestWorld-2.8.0-alpha1.jar

Upgraded from 1.12.2 Didn't touch any of my files.

15.01 21:14:21 [Server] WARN java.lang.NullPointerException
15.01 21:14:21 [Server] WARN at com.questworld.util.ResourceLoader.saveConfig(ResourceLoader.java:136)
15.01 21:14:21 [Server] WARN at com.questworld.util.ResourceLoader.saveConfigNoexcept(ResourceLoader.java:141)
15.01 21:14:21 [Server] WARN at com.questworld.extension.extras.Extras.onSave(Extras.java:41)
15.01 21:14:21 [Server] WARN at com.questworld.listener.ExtensionInstaller.onSave(ExtensionInstaller.java:39)
15.01 21:14:21 [Server] WARN at com.questworld.QuestingImpl.onSave(QuestingImpl.java:250)
15.01 21:14:21 [Server] WARN at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81)
15.01 21:14:21 [Server] WARN at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392)
15.01 21:14:21 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889)
15.01 21:14:21 [Server] WARN at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
15.01 21:14:21 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
15.01 21:14:21 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
15.01 21:14:21 [Server] WARN at java.lang.Thread.run(Thread.java:748)

**Comment by ezeiger92** [comment]
Did not mention it, this version supports 1.12/1.13 but directly switching between the two is not recommended. In this case try deleting the config-extras.yml file so it can be regenerated and see if it helps

**Comment by dejakob1** [comment]
Hello, the config-extras.yml was not present.
Running on a clean server with fresh generated files produced the same result.
I'll try to get some full logs. Are all the expansions working with 1.13.2?

**Comment by ezeiger92** [comment]
1.13.2 is my current test environment, and I am not getting that exception. Plenty of other bugs because I took a break from this project and alphas are rough, though. Yaaaaay....

**Comment by ezeiger92** [comment]
Alpha3 is out now, make sure you use QW-Legacy when running 1.12.2
