### ISSUE TITLE
Feature request / suggestion

### ISSUE THREAD

**Issue by Challenger8168** [ezeiger92/QuestWorld2#149]
I really enjoy using your plugin and it is the best plugin for quests out there.

But ther is one thing which is missing and kinda annoying.

I have a classes system and every class has 2 questlines, a default one, a class seperate one and a daily class seperate questline.

I want all the quests to be available via 1 NPc in their class house, but I cant tell the questbook, when they start which quest by clicking the npc.

So i would relly like to have a task for the quests, which, to complete, you have to click a specific button (designable) in the quest in the questbook itself, to activate the quest.

If you dont understand what I want, please re-text me.

Also, it would be great, for longer quests, to have up to 18 or more tasks for one quest, if that is possible.

Thank you for reading this.

Yours sincerely, CryoCrafter

**Comment by UltraFaceguy** [comment]
Actually, I kinda like this idea. I've had to design around not allowing multiple quests to be started by the same NPC for awhile now. A little GUI pop-up that lets you select which quest you're interacting with the NPC for would aid me as well.

Though, now that I think about it, wasn't there an 'Accept Quest From NPC' mission type? 🤔

**Comment by ezeiger92** [comment]
First things first: QuestWorld 2.8.0 supports unlimited tasks in a quest via a button at the top of the gui (rather than the fixed 9 tasks at the bottom of the gui)
Using "Accept Quest from NPC" will display a menu when there are multiple available quests, if that's what you're asking for.

Otherwise I'm not sure what you're asking for.

**Comment by ezeiger92** [comment]
Does my last comment cover what you're asking for, or am I missing something?
