### ISSUE TITLE
repeating is default

### ISSUE THREAD

**Issue by erik1988** [ezeiger92/QuestWorld2#15]
I noticed that the default is set to repeating for all new quests. Could you make the default single use? its bound to cause some issues since im used to all new quests being single use and all of my quests are  single use, I expect its the same for most people.

**Comment by ezeiger92** [comment]
You're not wrong, but you're also making me sad :(

**Comment by ezeiger92** [comment]
Fixed in push 40062843d9f9058346cc925b6006e625bf8a66eb, may be a little while before it gets into a build.
