### ISSUE TITLE
Feature: Option To Toggle Ding sound on every menu click.

### ISSUE THREAD

**Issue by RustyDagger** [ezeiger92/QuestWorld2#153]
I am asked if this can be changed Daily by my players it drives them nuts, and I agree its kind of annoying and not needed, a Simple config toggle would suffice or even the ability to change it to some other sound.

**Comment by ezeiger92** [comment]
That exists! Check out sounds.yml, you can set any sound for `quest.click` (quest menus), `party.click`, and `editor.click`. Look [here](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html) for a list of all sounds. You can also change the volume and pitch for each sound, so if you really don't want a sound, set the volume to 0

**Comment by RustyDagger** [comment]
wow how did i miss that
