### ISSUE TITLE
specials caracters

### ISSUE THREAD

**Issue by Arrandirs** [ezeiger92/QuestWorld2#156]
Hello hello ! I wanted to know how can i write special caracters like "ê" ? 
When i write it, i have '?' :/

**Comment by ezeiger92** [comment]
All files should be UTF-8, which would allow special characters and unicode. What were you editing and trying to put "ê" in?

**Comment by Arrandirs** [comment]
I try to rename the quest book to « Livre des quêtes » (in french) but i tryed with unicode and is it not work :/

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Erik <notifications@github.com>
Envoyé : Thursday, June 27, 2019 12:38:02 PM
À : ezeiger92/QuestWorld2
Cc : Arrandirs; Author
Objet : Re: [ezeiger92/QuestWorld2] specials caracters (#156)


All files should be UTF-8, which would allow special characters and unicode. What were you editing and trying to put "ê" in?

**Comment by ezeiger92** [comment]
What text editor are you using?

**Comment by Arrandirs** [comment]
Notepad++ x)

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Erik <notifications@github.com>
Envoyé : Thursday, June 27, 2019 12:49:06 PM
À : ezeiger92/QuestWorld2
Cc : Arrandirs; Author
Objet : Re: [ezeiger92/QuestWorld2] specials caracters (#156)


What text editor are you using?

**Comment by ezeiger92** [comment]
And just to make sure, are you saving the file with UTF-8 encoding?

**Comment by Arrandirs** [comment]
No:/ i’m sorry, my developper is on vacancies, i try to doing it without it but i have no real knowledge on developpement. I thought i just needed to use special langage and save it to have my caracter

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Erik <notifications@github.com>
Envoyé : Thursday, June 27, 2019 1:04:21 PM
À : ezeiger92/QuestWorld2
Cc : Arrandirs; Author
Objet : Re: [ezeiger92/QuestWorld2] specials caracters (#156)


And just to make sure, are you saving the file with UTF-8 encoding?

**Comment by ezeiger92** [comment]
In the top bar ("File", "Edit", "Search", ...) select "Encoding". Click "Convert to UTF-8" and save the file and see if that helps.

**Comment by Arrandirs** [comment]
Thanks you so much !


Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Erik <notifications@github.com>
Envoyé : Thursday, June 27, 2019 1:13:56 PM
À : ezeiger92/QuestWorld2
Cc : Arrandirs; Author
Objet : Re: [ezeiger92/QuestWorld2] specials caracters (#156)


In the top bar ("File", "Edit", "Search", ...) select "Encoding". Click "Convert to UTF-8" and save the file and see if that helps.

**Comment by ezeiger92** [comment]
No problem, I'm glad it worked out :)
