### ISSUE TITLE
a way to check stats

### ISSUE THREAD

**Issue by J3fftw1** [ezeiger92/QuestWorld2#159]
hey is there  a way to check stats of other players if not can there be a way to check player stats

**Comment by ezeiger92** [comment]
There's /qe progress <player> [category_id [quest_id]]
It's an admin command, and if you want to check an offline player you need to put their uuid.
The category and quest ids make no sense, so I suggest doing "/qe progress player" to find the category id you're looking for, then (if the id was 1) "/qe progress player 1" to find the quest id

At some point this will be changes around to be less hacky, but for now it does its job

**Comment by J3fftw1** [comment]
Thanks i would love to see the not hacky way
