### ISSUE TITLE
PaperMC 1.16.3 support

### ISSUE THREAD

**Issue by patricktsidina** [ezeiger92/QuestWorld2#168]
I was wondering since it's not listed in readme is PaperMC 1.16.3 supported?

**Comment by ezeiger92** [comment]
I don't list it because I don't test locally with paper, but it has been working without issue on my 1.16.3 paper server. Most bukkit/spigot plugins work without issue on paper. If you do run into issues, just let me know.

**Comment by patricktsidina** [comment]
Very well, thanks
