### ISSUE TITLE
Submit task at location

### ISSUE THREAD

**Issue by erik1988** [ezeiger92/QuestWorld2#17]
Feature request. 

I wonder if its possible to only accept an item when the player is in a specific quest location.  

Right now I usually activate order completion and  makes the player go to a special location and then a new task allow them to submit an item. The issue is that this allow the player to go home and submit the item from home. I wonder if it somehow would be possible to force them to be in a specific location?

**Comment by GershonR** [comment]
Can you try creating an NPC at a certain location and have a player submit through them?

**Comment by ezeiger92** [comment]
As usually happens, I got busy with some other private plugins and then hit a wall of dumb, so I'm back to this again.

@GershonR you are right, this would (probably, still haven't touched citizens) work, but it seems like a really simple thing that shouldn't require citizens to be installed.

**Comment by ezeiger92** [comment]
Will be able to try this out with the new stuff I pushed quite easily.

**Comment by ezeiger92** [comment]
Put in the "Extras" extension, I'll try to get a build out soon (today/tomorrow)
