### ISSUE TITLE
Click Block At Location [Feature]

### ISSUE THREAD

**Issue by UltraFaceguy** [ezeiger92/QuestWorld2#2]
Heya! One of the features I really wanted to see in the original QuestWorld was the ability to set a block location as a quest objective. Basically, the idea is, if the block clicked matches the exact location of your mission, objective complete. With it, you can do all sort of fun stuff with it, especially if you use head blocks at the target location. Let me know what you think!

Oh, and I've been using QuestWorld for awhile, and actually have my own version that I keep up to date. I actually already have the above finished and have for awhile. If you don't feel like adding it, would you mind if I'm given access to work on this repo? I have a few noice features I'd like to add when I have that time ;D

**Comment by ezeiger92** [comment]
I've been working on a way to make objectives easier to create, which would let requests like this be completed easily. It may take a while to complete due to college work, but after it's done I can add this feature.

**Comment by UltraFaceguy** [comment]
Yes, I see that. I've already converted what I had to your newer system with the quest types in their own classes. Looks nice so far! :D

**Comment by ezeiger92** [comment]
Same as I said on #3, will be added soon to test the new system.

**Comment by ezeiger92** [comment]
A WIP version is in the "Extras" extension right now, not even functional right now, just giving an update.

**Comment by ezeiger92** [comment]
Included in "Extras"
