### ISSUE TITLE
Crafting Tasks

### ISSUE THREAD

**Issue by Dalsok** [ezeiger92/QuestWorld2#23]
When players are to craft multiple items of something f.ex. 4 logs
if the player shift + click the crafted item it only counts as 4 planks, not 16 as it should be. 
Same goes for every item they craft

**Comment by ezeiger92** [comment]
Seriously? Man, some of this old code makes me really sad. Let me take a look.

**Comment by ezeiger92** [comment]
Should be fixed in the new release (2.6.5), let me know if this is still an issue.
