### ISSUE TITLE
Allow mobs from spawners from kill task

### ISSUE THREAD

**Issue by Dalsok** [ezeiger92/QuestWorld2#24]
The allowed mobs from spawners checkbox resets to true when the server restarts.

**Comment by ezeiger92** [comment]
LOL no, that doesn't appear to be quite right. You'll love this:

Quest.loadMissions passes in config.exclude_spawners when making the mission. This is assigned to mission.spawners
On save, it writes !mission.spawners into config.exclude_spawners

It flips back and forth every time it's saved xD
Okay, laughs aside, fixing this now :)

**Comment by Dalsok** [comment]
hehe, as long as it helps patch things up.

**Comment by ezeiger92** [comment]
Should be fixed in the new release (2.6.5), let me know if this is still an issue.
