### ISSUE TITLE
Money Task

### ISSUE THREAD

**Issue by MinecraftAdmin** [ezeiger92/QuestWorld2#3]
The ability to charge money to complete a task is oddly missing. Can this be easily implemented?

**Comment by ezeiger92** [comment]
I was busy and forgot to reply to this, but as with the other ticket, I'm holding off on adding more mission types until I have a better way to add them. I'm not sure how much free time I'll have between now and finals, so don't be too surprised if things move slowly :/

**Comment by ezeiger92** [comment]
If you are even still around, this will be added soon :)
I made at least 80% of the changes I wanted to make extensions easier, now I need things to test with and this will work brilliantly.

**Comment by ezeiger92** [comment]
Missed this request earlier. It's still rough around the edges but the Money extension adds this type. Builds soonish.
