### ISSUE TITLE
Unlimited mission support

### ISSUE THREAD

**Issue by ezeiger92** [ezeiger92/QuestWorld2#31]
Categories have properties (name, permission, etc) separate from the quests they contain, probably do the same for quests and missions.

**Comment by Zicerite** [comment]
Unlimited Tasks would be fantastic, we wouldn't ever have to worry about part 2's and 3's when they aren't necessary. I hope you are still pushing for this feature in the future :D

**Comment by ezeiger92** [comment]
Yes, this is still planned. I prioritized getting extensions done first (which they appear to be) because I'm still toying with how to implement this. I want to remove the current "ordered completion" mode, and instead let users set the ordering/requirements for any task individually.

**Comment by Zicerite** [comment]
Does that mean we could eventually make missions that could end in different ways with different rewards?

**Comment by ezeiger92** [comment]
Completed in 869f18898d0e6555bf1c3f21ec19fc4f4f2e948b
