### ISSUE TITLE
Request: Farming quest mechanic

### ISSUE THREAD

**Issue by Fharen** [ezeiger92/QuestWorld2#39]
I've requested this before on spigot discussion as Fritz. But I'm posting it here again for documentation and so you'll remember it sometimes :)

The problem with the current "block break" function is it can't have "crops" as target.
so having a "harvest" objective that could target all kinds of crops would be great.
having a "plant wheat" or any kind of crop objective would be nice as well.

this type of quest is ideal for daily quests. Hopefully you consider this 😅

**Comment by ezeiger92** [comment]
With the block break code that currently exists (fancy reflection magic), setting the block to wheat seeds will trigger when wheat is broken. That said, it doesn't do a great job because you can't detect crop levels with it. I'll see what I can do.

**Comment by ezeiger92** [comment]
Put in the "Extras" extension, might need some testing but I'm closing this for now. I'll try to have builds out soon (today/tomorrow)
