### ISSUE TITLE
Missing utility classes?

### ISSUE THREAD

**Issue by jjm223** [ezeiger92/QuestWorld2#4]
I'm not sure if I'm not seeing something or what, but it appears as though the project is missing the following utility classes:

- me.mrCookieSlime.QuestWorld.utils.SubmissionItemResolver
- me.mrCookieSlime.QuestWorld.utils.EntityTools

**Comment by ezeiger92** [comment]
I definitely missed those files, they are uploaded now. I need to better configure my svn...

**Comment by jjm223** [comment]
Thanks to you, too!
