### ISSUE TITLE
java.lang.ArithmeticException: / by zero

### ISSUE THREAD

**Issue by erik1988** [ezeiger92/QuestWorld2#40]
Got a server crash.

https://pastebin.com/VQ3E7n9g

**Comment by erik1988** [comment]
More info https://pastebin.com/Px2Q4Y04

**Comment by ezeiger92** [comment]
The server fired a craft event with a stack size of 0.... what? I can push out a fix, but I don't know how or why that happened.

Nothing about QuestWorld is listed in the crash report, that is likely a separate issue.

**Comment by ezeiger92** [comment]
https://github.com/ezeiger92/QuestWorld2/releases/tag/v2.6.7-beta
