### ISSUE TITLE
Cannot submit items

### ISSUE THREAD

**Issue by erik1988** [ezeiger92/QuestWorld2#41]
I have not had time to test this myself but several of my players has reported that when they try to submit items for quests they get removed from the inventory but nothing is added to the quest.

This started happening after the new bugfix release. Nothing shows up in console.

**Comment by ezeiger92** [comment]
Well I changed a bunch of stuff around there in code, must have not updated everything in sync. I'll try to take care of it tomorrow.

**Comment by ezeiger92** [comment]
https://github.com/ezeiger92/QuestWorld2/releases/tag/v2.6.7.1-beta
