### ISSUE TITLE
Detection is not working in the recent version

### ISSUE THREAD

**Issue by erik1988** [ezeiger92/QuestWorld2#42]
It does not automatically detecting location anymore, even if you wait very long. However it does work to click on it. Other detections does also not work. Like fishing quests.

**Comment by ezeiger92** [comment]
Well I tested and fishing, location, and normal detect missions all worked. Until they stopped working. Poop. Give me a bit.

**Comment by ezeiger92** [comment]
Oh god dammit, I update the ticking (detect) mission list using events, which works great when you create new missions. I didn't update that list when loading data from files. gaaaaaaaah

**Comment by erik1988** [comment]
Thanks. Will try it out when you release the build :)

**Comment by ezeiger92** [comment]
Just pushed the release, going to kill the old download now
