### ISSUE TITLE
Reach Location won't save and/or load Dialogue sometimes

### ISSUE THREAD

**Issue by Zicerite** [ezeiger92/QuestWorld2#43]
Reach Location as a first mission won't save the dialog sometimes, or at least won't read it from the .txt file. When it does save, sometimes no dialogue is loaded, and says the normal "You have completed a task (...)".
I've also noticed that it does save and load most of the time when its the 2nd mission onward, but rarely on the first mission.

I Hope my description helps

I have a pic of what it looks like, the first dialog line doesn't appear after the first mission, but the second mission's dialog does, and ive set the first one several times now, and idk whats going on
![2017-08-09_18 21 04](https://user-images.githubusercontent.com/30883277/29150451-8f640db4-7d2f-11e7-8deb-99e92bfc7455.png)

**Comment by ezeiger92** [comment]
I'll take a look, I have yet to touch dialog code and I'm sure it could use some work. Thanks!

**Comment by ezeiger92** [comment]
I broke it, whoops! Never got around to updating dialogue to the new system, meaning it's editing a copy of the mission rather than the actual mission.

**Comment by ezeiger92** [comment]
Question: Should having dialogue cause the normal "You completed X" to vanish?

**Comment by Zicerite** [comment]
Hmm... 
The only harm i see is that pre-existing quests would have to add a completion text line, but that seems fine to me.

So yeah, maybe make the "You completed X" vanish when dialog is added then, i'm for this idea.
