### ISSUE TITLE
Command Task

### ISSUE THREAD

**Issue by evernife** [ezeiger92/QuestWorld2#44]
Where is the command task?

I have upgrade from an older version of questworld to yours.
At that time i had "Command Tasks", but now, even though it is saying "command task" i just can't edit it '-'

![image](https://user-images.githubusercontent.com/11357801/29238126-6a8c83dc-7f04-11e7-9486-f4c459218ad3.png)

For me to do that i need the extension? [QuestWorld-Extensions](https://github.com/ezeiger92/QuestWorld-Extensions/tree/master/modules/ChatReaction/src/main/java/com/questworld/extensions/chatreaction)

If so, where can i download a compiled one ^^

**Comment by ezeiger92** [comment]
Oh man that's brilliant. I made that system for handling missing extensions, I didn't expect it to work for mission types from different branches!

You originally forked from CweepahCraft, who was the one that added the command mission. My branch never had it. I'm working on some more back-end stuff for extensions and general clean up, but I'll add this kind of mission to the "extras" extension when I can.
