### ISSUE TITLE
A sort of "Submit all" variant for mob kill quests, Reach Location, etc

### ISSUE THREAD

**Issue by Zicerite** [ezeiger92/QuestWorld2#47]
I honestly have no idea what to name this issue (request) report...

Currently kill quests involving multiple mobs need to be done 1 at a time, such as "Kill 5 Zombies" cool, now "Kill 5 Skeletons", etc. So that you would have to kill the zombies first, before registering any kills for Skeletons on the same quest.

I saw an issue post about a "Submit all" for items, and my idea is to do the same for "Kill Named Mob", "Kill Mob" and i guess "Kill Npc"

Now that im typing this, this could be interesting to add for all quest types, so that we could do stuff like this:

Mission 1: Accept quest from Npc
Mission 2: Kill 5 Skeletons, 4 Zombies, and 3 Creepers
Mission 3: Reach this location, and Reach this location
Mission 4: Citizens interact (Then quest is complete, in this example)

This could make all missions feel like a quest step, with a list of things to do first, before going onto the next mission.

**Comment by ezeiger92** [comment]
What in the world no please stop.
1. Missions have a singular focus. If you have to describe one as "... and ..." you need multiple missions. That will not change.
2. You can progress through multiple missions at the same time if "ordered completion" is turned off in the quest. If you need order, you are currently stuck with linear progression. This might be addressed with how I handle more missions in the future (#31).
3. "Submit All" (#38) was a request for a button to automatically check as many manual missions as possible (the ones you can click to check, like submit, detect, location, ...). I don't know what you thought it was, but that can't be applied to kill quests.

None of this makes sense :(

**Comment by Zicerite** [comment]
You're right, i have no idea what i just said, i apologize, greatly sorry ;-;
What i meant to say is that each mission would have multiple objectives
