### ISSUE TITLE
Task Suggestion - Complete a Quest N Times

### ISSUE THREAD

**Issue by evernife** [ezeiger92/QuestWorld2#48]
A task where you need to complete an Y QUEST n times:

For exemple.
There is a repeatable quest named "Kill 2555050 pigs"

If you complete that quest 10 times you complete another task.

(and just to illustrate  receves a tag_prefix "The PigKiller")

**Comment by ezeiger92** [comment]
That is an absurd amount of bacon. I'll consider the idea as an extension.

**Comment by ezeiger92** [comment]
Added events that are sent on quest completion a day ago or so. They make this suggestion possible.
