### ISSUE TITLE
Particle Options for NPC's who are Quest Starters

### ISSUE THREAD

**Issue by Zicerite** [ezeiger92/QuestWorld2#49]
The Title says most of what I was going to say..

Maybe have the ability to change how much, and what type of particle on the NPC that are quests starters, because the particles around the npc's are typically fine in large spaces, but its abit much in smaller spaces
And probably the frequency of when particles appear too.

![2017-08-22_17 25 54](https://user-images.githubusercontent.com/30883277/29593501-9056d910-875f-11e7-943b-b7dc540798fe.png)

**Comment by ezeiger92** [comment]
I haven't added a nice way for extensions to have their on configs, and I really haven't messed with citizens. I'll look at doing this eventually.

**Comment by ezeiger92** [comment]
I’ve finally figured out how I want this to work, I might be able to get around to it Tuesday.
