### ISSUE TITLE
Citizens Submit doesn't work

### ISSUE THREAD

**Issue by Kralleyo** [ezeiger92/QuestWorld2#51]
Citizens Submit doesn't work correctly. When I'm right clicking with the item nothing happens. 
I get this error in my console: "19.09 22:53:34 [Server] ERROR Could not pass event NPCRightClickEvent to QuestWorld v2.6.6"

Thank you for the awesome plugin by the way. If this would work everything would be perfect!

**Comment by Zicerite** [comment]
Doew this happen with version 2.6.7.2? And what Spigot version are you using?
I dont have this issue with 2.6.7.2, in 1.12

**Comment by Kralleyo** [comment]
I've tried 2.6.7.2. I'm running spigot 1.8.8 because of ViaVersion.

Thanks for the fast response by the way :)

**Comment by Zicerite** [comment]
This issue may be an issue with the older versions of minecraft. That's the only theory I have with this issue.

Unless Ezeiger92 has a different reason that may cause this issue.

**Comment by Kralleyo** [comment]
So there's nothing to do? I can't fix it somehow without changing Spigot version? :(

**Comment by ezeiger92** [comment]
I'm not supporting old versions of spigot, but if you provide the full stack trace I can see if there's an actual issue in the plugin rather than versions being incompatible.

**Comment by Kralleyo** [comment]
https://pastebin.com/NNevVqUW

Funny thing is the citizens submit works totally fine on MrCookieSlimes version on 1.8.8.

**Comment by ezeiger92** [comment]
I can confirm that exception is caused by using a version of spigot older than I use. Even if I changed my code, there's no guaruntee that other issues won't show up.

Sorry mate!

Cookie's version was built against an older spigot version and will eventually fail on newer versions of spigot.

**Comment by Kralleyo** [comment]
Dang it, thanks for the help tho :)
