### ISSUE TITLE
Can't change CITIZENS_SUBMIT's Citizen to submit to

### ISSUE THREAD

**Issue by Zicerite** [ezeiger92/QuestWorld2#53]
CITIZENS_SUBMIT's option to change which Citizen to submit to won't work.

I clicked on the option, the "Quest world > Please right click... blah blah blah" appears as normal, but when I right click the citizen, or any citizen for that matter, nothing happens.

Just in case i said something stupid or wrong, i left an image of which setting I'm not able to change.

![2017-09-26_20 50 50](https://user-images.githubusercontent.com/30883277/30895113-ef058e76-a2fc-11e7-99f2-8c9ef2763857.png)

**Comment by ezeiger92** [comment]
... What the fuck did I do to this code

**Comment by ezeiger92** [comment]
Replaced the link for citizens extension, try that one now. I really borked the code xD

**Comment by Zicerite** [comment]
Wow that was quick, thx i'll give it a shot 👍

**Comment by Zicerite** [comment]
Cool, Its works now, thx for the hotfix :)

**Comment by ezeiger92** [comment]
Thank goodness, I need to get sleep and don't really have the time to fix anything majorly wrong :x
