### ISSUE TITLE
Got stuck in Quest Description Entry

### ISSUE THREAD

**Issue by Zicerite** [ezeiger92/QuestWorld2#54]
Create's a quest, everything is fine.
Edits said quest's Quest Description, everything is fine.
But then when i try to make a new quest, I get stuck in the Quest Description edit thingy, everything i type in chat changes the Quest Description to what I say

I have an unlisted video of the issue:

https://www.youtube.com/watch?v=l9lH01WQW20&feature=youtu.be

**Comment by ezeiger92** [comment]
Fortunately a very small bug in the citizens extension. Give me a minute to fix and upload.

**Comment by ezeiger92** [comment]
Grab QW-Citizens 1.0.1 from the [latest release page](https://github.com/ezeiger92/QuestWorld2/releases/tag/v2.6.8-beta)

I had replaced cookie's code with my own, he returned "false" when done, I need "true" returned and forgot to change it. End result is input was never accepted.

**Comment by Zicerite** [comment]
Thanks
