### ISSUE TITLE
Leave/Delete Party automatically on logging off

### ISSUE THREAD

**Issue by Zicerite** [ezeiger92/QuestWorld2#56]
I think the title is self explanatory, maybe, idk...

Currently, once you are in a party, you stay in the party until you either leave it manually, or if the party leader deletes it manually.

Could you make it so that (or at least a config option? idk) that:
1. If the party leader logs off, the party is automatically deleted
2. If the player logs off, he/she automatically leaves the party

**Comment by ezeiger92** [comment]
Why do you want parties to work like that? Needing to re-add a player everytime they get dropped seems like a pain.

**Comment by Zicerite** [comment]
Hm... Good point

Ok, what about after a certain time has passed? like 5, or 10 minuites?

**Comment by ezeiger92** [comment]
But again, why do you want parties to work like that?

**Comment by Zicerite** [comment]
Because its weird to reset a party manually.
Minigame servers, ie Hypixel, always reset partys on logging off after some time has gone by, so that its quicker to create a new party

**Comment by ezeiger92** [comment]
I've always imagined parties in the DnD sense - the group tends to stick together for a long time and may have members swap in and out. That and I'm not sure quests with lore and progression are something that can be compared with mini-games, though that depends on your setup.

Is there a particular issue you're trying to solve, or do you just think that way makes more sense to you?

**Comment by Zicerite** [comment]
I was only requesting the option to auto party reset, since that's the norm with servers.
That's all I'm doing, and that's what makes most sense with rpg set ups; drop in/outs.

I asked my staff how I should explain why i requested this, some said basically players are on a different times on different days, so for a party system with drop in/outs with auto party resets on logging in/out.

Parties aren't always together in an online sense, This request was just one to add convenience to those with this set-up, as a config option or something

**Comment by ezeiger92** [comment]
Sorry mate, I really don't see where you're coming from on this one. A player missing a DnD session is not the same as a player leaving a party.
At some point I'm going to heavily modify the party system, which may address your concerns. For now I'm closing this issue.

**Comment by Zicerite** [comment]
Fair enough...

**Comment by ezeiger92** [comment]
Good new: a buddy who's actually played some MMOs agrees with you. Bad news: I still need to do a bunch of work on parties so this will take a while.

**Comment by Zicerite** [comment]
Oh, Thank you :)
