### ISSUE TITLE
Citizen Interact Missing Task Complete

### ISSUE THREAD

**Issue by GershonR** [ezeiger92/QuestWorld2#57]
After the dialogue has finished in a Citizen Interact task, there is no Task Complete message. It does show up in the Give Item task after that task, I could hardcode the message into the dialogue, but would rather see it fixed

**Comment by Zicerite** [comment]
Did you add dialogue into that task? If so, then that's why no "task completion" text doesn't show up. That was a change in the latest version.

If you didn't add any dialogue into that task, then yeah, that's likely a bug.

**Comment by GershonR** [comment]
Yeah i'm using dialogue, how come it was changed? It makes sense to say the task is finished once the NPC stopped talking

**Comment by Zicerite** [comment]
This change was so that you could put whatever message you wanted when a task was finished, such as
&7&oQuest Book has Updated
or whatever.

**Comment by ezeiger92** [comment]
It was removed on purpose as @Zicerite said, I'll look into an easy way to append that message. Probably will be adding "*" as the last line of dialog.

**Comment by ezeiger92** [comment]
It's _probably_ fixed in that commit. Using "*" as a dialogue line will fill in the end notification, just add that to the end of your dialogue list. I'll have time to verify (and re-fix, if needed) tomorrow. Not sure when a build will come out though.

**Comment by GershonR** [comment]
Is it possible to make a config option? Like edit the TASK_COMPLETE message and configure if you want it to show up at the end of a interact dialogue

**Comment by ezeiger92** [comment]
Again, the fix is add an asterisk as a line of dialogue to display the default message. It's the most general fix and offers the most flexibility.

Example:
- Thank you for doing the task
- *
- You should go do a new one now

Would display the first message, the "task complete" message, then the last message.
