### ISSUE TITLE
Text on several lines

### ISSUE THREAD

**Issue by erik1988** [ezeiger92/QuestWorld2#58]
Can you make it so that long text get split into several lines? 
Currently the text will go outside of the screen if its very long.
![2017-11-18_06 15 48](https://user-images.githubusercontent.com/3375321/32978438-a5ced464-cc42-11e7-9a50-9648add707fc.png)

**Comment by erik1988** [comment]
Thank you!

**Comment by ezeiger92** [comment]
I tried to do a build last weekend, and that clearly did not work. I'm just about at something stable currently, so we'll see what happens. Anyway here's a preview of text wrap in practice.

![name](https://user-images.githubusercontent.com/373934/33229061-40279512-d17c-11e7-9535-6b56d81f1d65.PNG)
![result](https://user-images.githubusercontent.com/373934/33229063-438c19d0-d17c-11e7-805b-39b35f0826e9.PNG)
