### ISSUE TITLE
[New feature?] Multiple Quests in one NPC

### ISSUE THREAD

**Issue by Ronnie0982** [ezeiger92/QuestWorld2#59]
Hello :)

I was wondering, if it was possible to make a npc have more than 1 quest, it's make in a GUI that will open when you right click on a npc with 2 or more quests. It will show a set of quests that the npc have, and when right clicking, the quests you wanna start, would start 👍 

Best regards
Ronnie // Ronnie0982

**Comment by ezeiger92** [comment]
Should have mentioned that I tried adding this, but did absolutely zero testing so I have no idea if the code works. Best kind of coding.
Might have time to work with it Tuesday, not sure when the next build will be ready though.
