### ISSUE TITLE
Not possible to submit weapons and tools.

### ISSUE THREAD

**Issue by erik1988** [ezeiger92/QuestWorld2#6]
For some reasons its not possible to submit weapons and tools anymore. Im using the latest version and spigot 1.11.2.

When I try to click it just make a sound but nothing happens.

**Comment by erik1988** [comment]
Seems like it works sometimes after a restart of the server. Its weird.

**Comment by erik1988** [comment]
Update: seems like after I have created a quest I need to restart the server to be able to submit stuff.

**Comment by ezeiger92** [comment]
Might have some time this weekend to take a look.

**Comment by erik1988** [comment]
I noticed that I had this problem with one quest that required tulips to be submitted. The server has been restarted many times after this quest was made so im not sure why it does not work. 

Are you any closer to fitgure out what is causing this? it used to work well before.

**Comment by erik1988** [comment]
I got it working by assigning the same flower again and restarting. I also made sure to update cs-lib to the latest version at the same time. Anyways. after a restart it worked again.

**Comment by erik1988** [comment]
nvm. turned out it still does not work. It was working with a test quest I made after a restart. But the original quest still dont work and if I delete the quest then they will lose their progress.

**Comment by erik1988** [comment]
I noticed that this guy has a fork that claims to have fixed the bug. Maybe you can merge it into yours if it looks okay?

**Comment by ezeiger92** [comment]
Finally got back to this; the problem appears to be item1.isSimilar(item2) fails when item2 is the type "CustomItem" and item1 is not. His fix is "swap the order if it's a custom item", I've made a fix that should prevent CustomItem from being used in that check at all.

I'm going to clean up a few things and commit

**Comment by erik1988** [comment]
Thanks!

**Comment by erik1988** [comment]
Any updates on when you will publish the new version?

**Comment by ezeiger92** [comment]
I'll stop being lazy and push it in a little while. There will be a somewhat breaking change with quest cooldowns (namely 0 cooldown means no cooldown, -1 means "only once")

**Comment by ezeiger92** [comment]
[Done](https://github.com/ezeiger92/QuestWorld2/releases/tag/v2.6.3-beta). This should all be fixed now.
