### ISSUE TITLE
Very Minor text bug with Category Display

### ISSUE THREAD

**Issue by Zicerite** [ezeiger92/QuestWorld2#61]
Version 2.6.9

When a category has 6 quests in it, in its preview info box thingy, it will say "and -1 more..." instead of "and 1 more..."
This doesn't happen if there's more than 6 quests in the category.

![2017-11-26_19 51 43](https://user-images.githubusercontent.com/30883277/33248700-986076a0-d2e3-11e7-9bad-5cde62cf8fff.png)
![2017-11-26_19 51 45](https://user-images.githubusercontent.com/30883277/33248705-9c78e808-d2e3-11e7-982c-9ed04312ca74.png)
![2017-11-26_19 52 34](https://user-images.githubusercontent.com/30883277/33248709-9ec5c4dc-d2e3-11e7-930e-2a9e222a3753.png)

**Comment by ezeiger92** [comment]
That's awesome, I think I know what's up.
