### ISSUE TITLE
[Bug or my mistake?] Console errors on resetting quest database

### ISSUE THREAD

**Issue by Zicerite** [ezeiger92/QuestWorld2#62]
Title ^

All i did was hit the Delete Database button on quests I was resetting, and this happens.
Was there something i was supposed to reset in the 2.6.9 update, or is this a bug?

The Quest progress does reset as intended, just the console error idk about.

![mistakemaybe](https://user-images.githubusercontent.com/30883277/33253228-ad6f7e6c-d2ff-11e7-9144-6622fd0f9ccd.png)

**Comment by ezeiger92** [comment]
Looks like it tried to save and load a UUID directly, I must have failed to change it to a string before saving. I'll try to fix this one really quick because that could actually screw stuff up for you later.

**Comment by ezeiger92** [comment]
`public void setPartyLeader(UUID uuid) {
		config.set("party.associated", uuid);
	}`
Found it. Dammit lol

**Comment by Zicerite** [comment]
Good to know that this could mess everything up, i haven't touched any of my quests since i saw this lol, thx

**Comment by ezeiger92** [comment]
Alright, build up at https://github.com/ezeiger92/QuestWorld2/releases/tag/v2.6.9.1-beta

Looking at that exception, it definitely wrote the UUID's to some player data files already, which means they'll probably need to be manually fixed :x
Do you have a rough idea of how many people were online when you used 2.6.9?

**Comment by Zicerite** [comment]
luckilly just 2, me and my tester
We test plugin updates when they come. Luckilly i caught this lol

**Comment by ezeiger92** [comment]
<3
I'm guessing both of your player files (data-storage/Quest World/ -uuid- .yml) will have `!!java.util.UUID` in them. If you remove them and use the new build, it should work normally.

**Comment by Zicerite** [comment]
I see, thank you. I'll continue to keep looking for more issues.
