### ISSUE TITLE
NPC's with Quests Particle issue

### ISSUE THREAD

**Issue by Zicerite** [ezeiger92/QuestWorld2#63]
This is an odd one.
When near an NPC of which you can accept quests from, they lose their particle effect, and the player near them takes the particle effect instead.

![2017-11-26_23 23 56](https://user-images.githubusercontent.com/30883277/33253571-3a561466-d301-11e7-9b22-cfd65ecca275.png)
![2017-11-26_23 24 18](https://user-images.githubusercontent.com/30883277/33253572-3a68e956-d301-11e7-8974-8feb5de0608e.png)

**Comment by ezeiger92** [comment]
Hah. Hahahahaha. Ha. Yea, I know why that happened, a function did a different thing than I thought it did.

**Comment by ezeiger92** [comment]
Updated the QW-Citizens to 1.1.1 on the release page.
Very silly of me, wasn't even "this thing worked differently than I thought", I just told the server to spawn particles on the player because I forgot to change it to the npc. gg myself.

**Comment by Zicerite** [comment]
lol, thank you for the fix.
