### ISSUE TITLE
Descriptions Missing?

### ISSUE THREAD

**Issue by doitliketyler** [ezeiger92/QuestWorld2#65]
There used to be an option to add descriptions for a quest but I no longer see it. Am I blind or did you remove it? I hope I'm just blind because removing a quest description doesn't make sense.

**Comment by Zicerite** [comment]
Make sure everything is up to date, since there is a new version for the plugin itself, and the extensions.
idk why descriptions would be done...

**Comment by ezeiger92** [comment]
Didn’t have time to test, but looking at the code it should still be there.

For clarity, do you mean the “description” setting only available on Accept Quest missions, or the custom mission display which lets you change the display name?

**Comment by doitliketyler** [comment]
Everything is definitely up to date. There should be an option to set descriptions for a quest and once upon a time it was there. As of right now, all I see is an option to set the name and icon so when a player goes to do a quest they just see the name and set of tasks but have no idea why they are doing these tasks. Makes for a weird experience.

**Comment by ezeiger92** [comment]
I have only ever seen the option to change mission names, not an option to add a description for quests. Is this what you were thinking of? If not, I'd like to know what version you thought this option was on.
![2017-12-04_07 07 28](https://user-images.githubusercontent.com/373934/33559544-000b3d38-d8c2-11e7-98bd-d4d608edaf61.png)
![2017-12-04_07 07 53](https://user-images.githubusercontent.com/373934/33559556-0790e2d8-d8c2-11e7-9235-20158e4b82b0.png)
*shrugs*

**Comment by doitliketyler** [comment]
No, I mean the quest description. I couldn't tell you what version it was but I've been using QuestWorld since the first day it was released and it was there. I did some digging and I found this as proof:

https://imgur.com/a/s6uaP

**Comment by ezeiger92** [comment]
That is from the Accept Quest mission, and is actually part of the mission and not the quest. The "quest description", despite horrible naming, is still part of that mission. These are from the current version:

![2017-12-05_00 25 43](https://user-images.githubusercontent.com/373934/33597073-16c9a942-d953-11e7-9c35-36a7c4fea593.png)
![2017-12-05_00 25 53](https://user-images.githubusercontent.com/373934/33597083-1ac0779c-d953-11e7-82fa-636a47497f4a.png)

**Comment by doitliketyler** [comment]
Ahhh...I see it now. That should really be an option outside of NPC's as well. Most of the games I play revolve around questing and literally every single one of them has an intro description and all of my quests definitely need them or they are just names followed by tasks with literally no meaning whatsoever.
