### ISSUE TITLE
Error Code with the newest Build

### ISSUE THREAD

**Issue by MysticCity** [ezeiger92/QuestWorld2#66]
07.12.2017 19:01:53 [WARNING] [QuestWorld] Task #58 for QuestWorld v2.6.9.1 generated an exception
07.12.2017 19:01:53 java.lang.NumberFormatException: For input string: "2592000000"
07.12.2017 19:01:53 	at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:1.8.0_144]
07.12.2017 19:01:53 	at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_144]
07.12.2017 19:01:53 	at java.lang.Integer.valueOf(Unknown Source) ~[?:1.8.0_144]
07.12.2017 19:01:53 	at me.mrCookieSlime.QuestWorld.quest.Quest.fromMaybeString(Quest.java:90) ~[?:?]
07.12.2017 19:01:53 	at me.mrCookieSlime.QuestWorld.quest.Quest.<init>(Quest.java:101) ~[?:?]
07.12.2017 19:01:53 	at me.mrCookieSlime.QuestWorld.quest.RenderableFacade.load(RenderableFacade.java:107) ~[?:?]
07.12.2017 19:01:53 	at me.mrCookieSlime.QuestWorld.QuestWorldPlugin.load(QuestWorldPlugin.java:134) ~[?:?]
07.12.2017 19:01:53 	at me.mrCookieSlime.QuestWorld.QuestWorldPlugin.lambda$onEnable$0(QuestWorldPlugin.java:82) ~[?:?]
07.12.2017 19:01:53 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
07.12.2017 19:01:53 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
07.12.2017 19:01:54 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
07.12.2017 19:01:54 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
07.12.2017 19:01:54 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
07.12.2017 19:01:54 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
07.12.2017 19:01:54 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]

**Comment by MysticCity** [comment]
And this Spams in the Console:

07.12.2017 19:05:25 [WARNING] [QuestWorld] Task #59 for QuestWorld v2.6.9.1 generated an exception
07.12.2017 19:05:25 java.lang.NullPointerException: null
07.12.2017 19:05:25 	at me.mrCookieSlime.QuestWorld.manager.PlayerManager.getStatus(PlayerManager.java:178) ~[?:?]
07.12.2017 19:05:25 	at me.mrCookieSlime.QuestWorld.manager.PlayerManager.update(PlayerManager.java:145) ~[?:?]
07.12.2017 19:05:25 	at me.mrCookieSlime.QuestWorld.QuestWorldPlugin.lambda$loadConfigs$1(QuestWorldPlugin.java:113) ~[?:?]
07.12.2017 19:05:25 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
07.12.2017 19:05:25 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
07.12.2017 19:05:25 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
07.12.2017 19:05:25 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
07.12.2017 19:05:25 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
07.12.2017 19:05:25 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
07.12.2017 19:05:25 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]


No Quests Loaded

**Comment by ezeiger92** [comment]
Good lord

**Comment by ezeiger92** [comment]
You have a quest on a 30 day cooldown. That's beyond int capacity. Great.

**Comment by MysticCity** [comment]
yes 7 day and 30 day

**Comment by ezeiger92** [comment]
Well that was a nightmare. Bug should be fixed, just replaced the latest build (it looks the same). Let me know how it goes

Now the project has multiple branches like it always should have.

**Comment by MysticCity** [comment]
okay work fine.....
