### ISSUE TITLE
Cannot leave quest party

### ISSUE THREAD

**Issue by erik1988** [ezeiger92/QuestWorld2#7]
I have had many players reporting that they are unable to leave their quest party. They are clicking the red wool but nothing happens.

**Comment by ezeiger92** [comment]
So many fun things! I think parties just need a rewrite, even without bugs I don't like how they function.

**Comment by ezeiger92** [comment]
Failed to autoclose, looks like I haven't mastered that yet. Should be the same issue as 34, and should be fixed
