### ISSUE TITLE
It says summit "inc sac" when it should say "bone meal". 

### ISSUE THREAD

**Issue by erik1988** [ezeiger92/QuestWorld2#74]
![image](https://user-images.githubusercontent.com/3375321/34311820-3100b358-e760-11e7-9a7b-608636131f2d.png)
![image](https://user-images.githubusercontent.com/3375321/34311824-3b48ef38-e760-11e7-84a2-3e20f801b1cb.png)

I used your latest build.

**Comment by ezeiger92** [comment]
What’s your bukkit version?

**Comment by erik1988** [comment]
![image](https://user-images.githubusercontent.com/3375321/34312425-6265fbc0-e764-11e7-9bdb-c7bf2c26fce1.png)

**Comment by ezeiger92** [comment]
“Submit at” uses the old-school name method of “take the material name and print it nicely”, that’s my bad.

That warning is known and the fix is already in place, I just haven’t switched it yet for backwards compatibility.

**Comment by erik1988** [comment]
Thanks!

**Comment by erik1988** [comment]
Thanks for fixing this. Are you planing to make a new release soon? Would be nice to get a version were this is fixed. Thanks!

**Comment by ezeiger92** [comment]
How about right now https://github.com/ezeiger92/QuestWorld2/releases/tag/v2.6.10-RC1

**Comment by erik1988** [comment]
Wow! You are awesome! I appreciate your work!
