### ISSUE TITLE
CITIZENS SUBMIT doesn't take skull with lores

### ISSUE THREAD

**Issue by Tarka-Dhal** [ezeiger92/QuestWorld2#75]
As title. :)

**Comment by ezeiger92** [comment]
Set the lore of the mission item to a single asterisk `*`, that will ignore metadata when comparing items.
If you are trying to accept a specific player skull AND ignore lore, you are currently out of luck.

**Comment by Tarka-Dhal** [comment]
I'm trying to compare skull with lore.

**Comment by Tarka-Dhal** [comment]
Do you think that you can fix it?

**Comment by Worlfy** [comment]
Why close it? It's not that hard to make it support lores

**Comment by ezeiger92** [comment]
I closed this because a feature already exists to ignore lore in item comparisons. Unfortunately it looks like I don’t use it any submit missions. Whoops. Reopening to address that bug.

**Comment by Tarka-Dhal** [comment]
It only doesn work with heads.
