### ISSUE TITLE
MythicMobs support

### ISSUE THREAD

**Issue by Worlfy** [ezeiger92/QuestWorld2#76]
Hey,

I'd like to see some MythicMobs support so I can specifiy what custom mobs they need to kill for a quest

Kind regards

**Comment by ezeiger92** [comment]
Have you tried using the “kill named mob” mission type? It can accept a colored (and partial) name, which should be plenty of control for special mobs.

**Comment by Worlfy** [comment]
Gotcha, thanks. Was kinda tired when I thought of it ;P
What about a feature to talk to npc's?

- Talk to npc
- Kill x
- Talk again
- Do something else

**Comment by ezeiger92** [comment]
Grab the QW-Citizens extension and put it in the extensions folder, it adds mission types for npc interact, submit, kill, and “accept quest”. That last one is a bit odd and needs work.

For that extension to work, you’ll need Citizens and CS-CoreLib on your server. It’s the only bit of code that still relies on CS-CoreLib :(

**Comment by Worlfy** [comment]
Gotcha, thanks a lot! ^-^
