### ISSUE TITLE
NPE without stacktrace

### ISSUE THREAD

**Issue by Worlfy** [ezeiger92/QuestWorld2#77]
So I'm being spammed with this

![image](https://user-images.githubusercontent.com/8803519/34328656-0988bd6c-e8e5-11e7-94bb-5083afe938eb.png)

No stacktrace, no nothing.
What configurations would you like to see?

**Comment by ezeiger92** [comment]
Something happened during startup, please send me the full server log.

**Comment by Worlfy** [comment]
![image](https://user-images.githubusercontent.com/8803519/34328665-881534a8-e8e5-11e7-9e21-eee9220d3cea.png)

**Comment by ezeiger92** [comment]
That's not the full log :P
As a random guess from that *maybe* you have an older version of QW-Citizens, although that shouldn't load in the first place.

**Comment by Worlfy** [comment]
What about this?

![image](https://user-images.githubusercontent.com/8803519/34328715-a22a5aca-e8e6-11e7-86cb-9b210283322e.png)

**Comment by ezeiger92** [comment]
I need to see the `latest.log` file, that's the entire server log. You can upload it to something like hastebin.com or paste the contents it in here between ` ```contents``` `

**Comment by Worlfy** [comment]
https://hastebin.com/idarusowox.bash

This should do

**Comment by ezeiger92** [comment]
That looks like an issue I already fixed, which means your quest files may be screwed up. Could you `/qe export preset` and send me the zip?

**Comment by Worlfy** [comment]
[preset.zip](https://github.com/ezeiger92/QuestWorld2/files/1585033/preset.zip)

**Comment by ezeiger92** [comment]
I'm not getting those messages, could you download the latest version again?

**Comment by Worlfy** [comment]
I did

**Comment by ezeiger92** [comment]
If you're still having issues, I'm not sure what's going on. Try running with just questworld, citizens, and cs-corelib.

**Comment by Worlfy** [comment]
I'll try, will leave another comment with the result

**Comment by Worlfy** [comment]
![image](https://user-images.githubusercontent.com/8803519/34328946-18219038-e8ef-11e7-976b-78dd02eeb04d.png)

Got that when I do /quests, startup error stays the same and I'm still being spammed

**Comment by ezeiger92** [comment]
I'm not having any of these issues with the current builds. Either there is something wrong in your quest playerdata file or there is something wrong with your questworld jar. 

Stop your server, remove the quest playerdata directory (default `data-storage/Quest World/`), and start it again.

If you are still getting the same errors, I'll need to take a look at your questworld.jar file.

**Comment by Worlfy** [comment]
Removing the player-data and restarting the server m

**Comment by Worlfy** [comment]
Happens when I /reload my server, never goes away

**Comment by ezeiger92** [comment]
Questworld is not /reload safe. Eventually it might be, but that is a long way off. /qe reload quests and /qe reload config will let you reload data safely.

**Comment by Worlfy** [comment]
Just happened again when I simply did a quest

**Comment by ezeiger92** [comment]
Then I need to see your questworld jar.

**Comment by Worlfy** [comment]
[QuestWorld-2.6.9.1.zip](https://github.com/ezeiger92/QuestWorld2/files/1585064/QuestWorld-2.6.9.1.zip)

**Comment by ezeiger92** [comment]
I cannot reproduce any of your issues without use of /reload. Using /reload is not supported by QuestWorld and will break things. I'm not fixing issues caused by /reload.
