### ISSUE TITLE
Detect not automatically working?

### ISSUE THREAD

**Issue by clndkstr** [ezeiger92/QuestWorld2#8]
Hello,

I have a small question about the detect option. Does it only work with the manual detect option or does it also has to work automatically? Because at the moment it only works with the manual detect. Am i doing something wrong or is this a bug? I'm sorry for the bad English.
I hope to hear from you soon!

**Comment by ezeiger92** [comment]
I've been using automatic detect for killing mobs, which has been working just fine. What kind of quest were you using? (kill mob, submit item, ...)

**Comment by clndkstr** [comment]
I used the option that you had to find an item, and as soon as you have it in your inventory it would complete the task. (It's the option with the commandblock as logo).

**Comment by ezeiger92** [comment]
This may be related to the item compare issue in ezeiger92/QuestWorld2#6. Pushing a fix for that one now.

**Comment by ezeiger92** [comment]
Haven't checked back on this for too long, have any of the recent builds fixed this, or is it still an issue?

**Comment by ezeiger92** [comment]
Well I don't know if it got fixed and then I unfixed it, but I just noticed Detect was not a Ticking task. Whoops. Fixed as of 9335ef7191e2b6f65b1bc7bb718547442673baa7
