### ISSUE TITLE
bug quest fishing 

### ISSUE THREAD

**Issue by Yukyxy** [ezeiger92/QuestWorld2#99]
Hello I found a bug, in my quest I have to fish a globe fish, I fished a leather chest, the quest has been validated ...

https://zupimages.net/up/18/05/624u.png

**Comment by Zicerite** [comment]
Which spigot and plugin version are you using?

**Comment by Yukyxy** [comment]
sorry 1.12

**Comment by ezeiger92** [comment]
Unable to reproduce with QuestWorld 2.6.10
